name: BetterHome
main: es.serversurvival.main.Main
version: 1.0
api-version: "1.16"
author: JaimeTruman
commands:
  home:
    description: command related with homes
    usage: /<command>
  sethome:
    description: add a new home
    usage: /<command>
  viewhomes:
    description: xd